### ISSUE TITLE
fix .inf

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_autoit_helper#7]
1) homepage= не заполнено. Нельзя перейти на страницу из addon manager

2) 
[item2]
section=events
events=on_key
keys=9

может тут добавить lexers=AutoIt ? надо проверить что тогда плагин не будет грузиться от Таба в любом файле.

**Comment by OlehL** [comment]
Поправил 1, 2.
Проверил - плагин грузиться после tab только для AutoIt лексера.

**Comment by Alexey-T** [comment]
Выложил плаг
